//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUIFlightManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public System.Guid Id { get; set; }
        public string CodeName { get; set; }
        public System.Guid DepartureAirportId { get; set; }
        public System.Guid DestinationAirportId { get; set; }
        public System.Guid AircraftId { get; set; }
        public decimal FuelConsumption { get; set; }
        public decimal Distance { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificatonDate { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airport DepartureAirport { get; set; }
        public virtual Airport DestinationAirport { get; set; }
    }
}
